#!/usr/bin/env python
from __future__ import print_function
from glob import glob

import argparse
import getpass
import json
import os
import re
import shutil
import signal
import socket
import subprocess
import sys
import time

try:
    from urllib2 import urlopen, HTTPError
except ImportError:
    from urllib.request import urlopen
    from urllib.error import HTTPError

try:
    input = raw_input
except NameError:
    pass

DAEMON_BIN_NAME = 'adsd'


def eprint(*args, **kwargs):
    """
    https://stackoverflow.com/a/14981125

    :param args: print args
    :param kwargs: print kwargs
    :return:
    """
    print(*args, file=sys.stderr, **kwargs)


def save_config(filepath, settings):
    """
    Save config in ADS format:

    key=value
    (one per line)

    A value can be a list (eg. [val1, val2]). This will be written like this:

    key=val1
    key=val2

    :param filepath: Config file path.
    :param settings: Dictionary of settings.
    :return:
    """
    with open(filepath, 'w') as f:
        for k, v in sorted(settings.items()):
            if isinstance(v, list):
                for seq_el in v:
                    f.write("{0}={1}\n".format(k, seq_el))
            else:
                f.write("{0}={1}\n".format(k, v))


class GenesisFile(object):
    """
    Genesis file object, with helper functions.
    """
    def __init__(self, genesis_file):
        """
        Read the file in.

        :param genesis_file: Genesis filepath or URL
        """

        if genesis_file.startswith('http'):
            try:
                genesis_response = urlopen(genesis_file)
                self.genesis_raw = genesis_response.read()
                self.genesis = json.loads(self.genesis_raw)
            except ValueError as e:
                eprint("Error decoding remote genesis file. Make sure it's a plain text file in json format.", e)
                sys.exit(1)
            except HTTPError as e:
                eprint("Unable to retrieve remote genesis file.", e)
                sys.exit(1)
        else:
            try:
                with open(genesis_file, 'r') as f:
                    self.genesis_raw = genesis_file.read()
                    self.genesis = json.loads(self.genesis_raw)
            except ValueError as e:
                    eprint("Error decoding local genesis file. Make sure it's a plain text file in json format.", e)
                    sys.exit(1)
            except IOError as e:
                eprint("Unable to open local genesis file ({0}).".format(e))
                sys.exit(1)

        self._genesis_dict()

    def _genesis_dict(self):
        self.nodes = {}
        for index, node in enumerate(self.genesis['nodes']):
            node_ident = '{0:04x}'.format(index + 1)
            self.nodes[node_ident] = node

    def node_identifier_from_public_key(self, pub_key):
        for node_id in self.nodes.keys():
            if self.nodes[node_id]['public_key'] == pub_key:
                return node_id

    def save(self, filepath):
        with open(filepath, 'w') as f:
            json.dump(self.genesis_raw, f)


def validate_platform(verbose=False):
    """
    Check if you can run ADS. Currently supported only on 64 bit Linux.

    :return: Exits with status code 1 if platform is not valid, otherwise just prints out some system information.
    """

    # Platform check, linux or windows, or something else
    if not sys.platform.startswith('linux'):
        eprint("This platform is not supported for this configuration script.")
        eprint("I need 'linux', but this is '{0}'. See manual configuration instructions.".format(sys.platform))
        sys.exit(1)

    # Architecture check
    try:
        uname_data = os.uname()
        if uname_data[4] != 'x86_64':
            eprint("This architecture is not supported. I need *x86_64*.")
            sys.exit(1)
    except AttributeError:
        eprint("Can't detect the architecture. I need a *nix system to do that.")
        sys.exit(1)

    if verbose:
        print("Detected: {0} {1}".format(sys.platform, os.uname()[4]))


def get_my_ip(remote_ip="8.8.8.8", remote_port=53):
    """
    Try to connect to remote ip, to get local interface address. Defaults to google DNS.

    :param remote_ip: Remote ip to connect to.
    :param remote_port: Remote port to connect to.
    :return: Local interface ip.
    """

    # https://stackoverflow.com/a/166589

    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect((remote_ip, remote_port))
    my_ip = s.getsockname()[0]
    s.close()

    return my_ip


def prepare_node_configuration(node_id, genesis_data, private_key, node_ident_genesis=None):

    if node_ident_genesis:
        print("Found matching public key in genesis.")
        # Check if private key matches public key in the chosen identifier
        if node_id and node_ident_genesis != node_id:
            eprint("Invalid private key for node: {0}".format(node_id))
            sys.exit(1)

        # Node id taken from matching public key
        node = genesis_data.nodes[node_ident_genesis]
        node['_nid'] = node_ident_genesis

        print("Configuring nodes: {0}".format(node_ident_genesis))
    else:
        print("No matching public key found in genesis file.")
        # New node (not in genesis)
        if not node_id:
            eprint("No node number provided to set up new node. Did you forget --node?")
            sys.exit(1)

        node = {'_nid': node_id,
                'accounts': []}
        print("Configuring new node: {0}".format(node_id))

    node['_secret'] = private_key
    return node


def configure(config, genesis_data, node_ident_genesis=None):
    """
    Configure nodes and their first account

    :return:
    """
    node = prepare_node_configuration(config.node, genesis_data, config.private_key, node_ident_genesis)

    if not node:
        print("No nodes to configure.")
        sys.exit(1)

    if not os.path.exists(config.working_dir):
        os.makedirs(config.working_dir)

    genesis_data.save(os.path.join(config.working_dir, 'genesis.json'))

    private_key_dir = os.path.join(config.working_dir, 'key')

    if not os.path.exists(private_key_dir):
        os.makedirs(private_key_dir)

    os.chmod(private_key_dir, 0o700)

    with open(os.path.join(private_key_dir, 'key.txt'), 'w') as f:
        f.write(node['_secret'])

    os.chmod(os.path.join(private_key_dir, 'key.txt'), 0o600)

    nconf = {'svid': int(node['_nid'], 16),
             'port': 6510,
             'offi': 6511,
             'addr': config.interface}

    filepath = os.path.join(config.working_dir, 'options.cfg')

    save_config(filepath, nconf)
    print("{0} Saved options to: {1}".format(node['_nid'], filepath))


def get_public_key(private_key):
    proc = subprocess.Popen(['ads', '-s'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, errors = proc.communicate(private_key)
    match = re.search('Public key: (.*?)\s', errors)
    if match:
        return match.group(1)


def get_nodeid_from_genesis(genesis_data, private_key):
    pub_key = get_public_key(private_key)
    return genesis_data.node_identifier_from_public_key(pub_key)


def action_signal(working_dir, chosen_signal, name):
    """
    Send a signal to daemon

    :param working_dir: Path to directory holding the pid file.
    :param chosen_signal: Signal sent to daemon.
    :param name: Name of action.
    :return:
    """
    pid = get_daemon_pid(working_dir)
    if not pid:
        print("{0} not running in {1}.".format(DAEMON_BIN_NAME, working_dir))
    else:
        try:
            os.kill(pid, chosen_signal)
            print("ADS node {0} {1} was successful.".format(working_dir, name))
        except OSError:
            print("ADS node {0} {1} has failed.".format(working_dir, name))


def action_configure(conf_args):

    genesis_data = GenesisFile(conf_args.genesis_url)

    conf_args.private_key = getpass.getpass("Node's private key: ")
    print("Default values are in []. Press enter to choose them.")

    node_ident_genesis = get_nodeid_from_genesis(genesis_data, conf_args.private_key)
    if node_ident_genesis:
        print("Public key for your private key found in genesis file. Associated node identifier is {0}.".format(node_ident_genesis))
        conf_args.node = input("Node identifier [{0}]: ".format(node_ident_genesis))
        if not conf_args.node:
            conf_args.node = node_ident_genesis
    else:
        print("Public key for your private key not found in genesis file. Associated node identifier is {0}.".format(node_ident_genesis))
        conf_args.node = input("Node identifier: ")

    conf_args.interface = input("Node interface [{0}]): ".format(get_my_ip()))
    if not conf_args.interface:
        conf_args.interface = get_my_ip()

    configure(conf_args, genesis_data, node_ident_genesis)


def get_daemon_pid(working_dir=None):
    """
    Finds running adsd daemons.

    :param working_dir: Find specific daemon (optional)
    :return: Process identifier (pid) or None if no adsd daemons are running.
    """
    try:
        if working_dir:
            pid = subprocess.check_output(['pgrep', '-f', '{0}.*--work-dir={1}'.format(DAEMON_BIN_NAME, working_dir)])
        else:
            pid = subprocess.check_output(['pgrep', DAEMON_BIN_NAME])
            pid = pid.strip().split('\n')[0]  # Only one adsd should be running
        return int(pid)
    except subprocess.CalledProcessError:
        return None


def action_start(working_dir):
    """
    :param working_dir: Path to node configuration directory.
    :return:
    """

    if not os.path.exists(working_dir):
        print("Working directory {0} does not exist.".format(working_dir))
        sys.exit(1)

    genesis_path = os.path.join(working_dir, 'genesis.json')

    cmd = [
        DAEMON_BIN_NAME,
        '--genesis={0}'.format(genesis_path),
        '--work-dir={0}'.format(working_dir)
    ]

    # Is node part of genesis or is it started again
    with open(os.path.join(working_dir, 'key', 'key.txt'), 'r') as f:
        private_key = f.read()

    genesis_data = GenesisFile(genesis_path)
    node_ident_genesis = get_nodeid_from_genesis(genesis_data, private_key)

    if not node_ident_genesis and not glob(os.path.join(working_dir, 'usr', '*.dat')):
        cmd += ['-f', '1']

    stdout = open(os.path.join(working_dir, '{0}.log'.format(DAEMON_BIN_NAME)), 'w')
    stderr = open(os.path.join(working_dir, 'error.log'), 'w')

    proc = subprocess.Popen(cmd, stdout=stdout, stderr=stderr)

    try:
        os.kill(proc.pid, 0)
        print("Process started: ", time.strftime("%Z - %Y/%m/%d, %H:%M:%S", time.localtime(time.time())))
    except OSError:
        eprint("Server not started.")
        sys.exit(1)

    print("ADS node {0} started.".format(working_dir))


def action_clean(working_dir):
    """
    Remove and recreate the whole ADS data directory.

    :param working_dir: Directory to clean up.
    :return:
    """
    if os.path.exists(working_dir):
        shutil.rmtree(working_dir)
        os.mkdir(working_dir)
        print("ADS node configuration removed.")
    else:
        print("{0} doesn't exist".format(working_dir))


def prepare_args():

    if 'USER' in os.environ.keys():
        # Support for sudo
        default_working_dir = os.path.join(os.path.expanduser("~" + os.environ["USER"]), ".adsd")
    else:
        default_working_dir = os.path.expanduser("~/.adsd")

    default_genesis_url = 'https://raw.githubusercontent.com/adshares/ads/master/genesis.json'

    parser = argparse.ArgumentParser(description='Maintenance service for the ADS network.')
    parser.add_argument('action', choices=['start', 'stop', 'restart', 'configure', 'status'])
    parser.add_argument('-w', '--working-dir', default=default_working_dir, help='working directory (default "{0}")'.format(default_working_dir))
    parser.add_argument('-g', '--genesis-url', default=default_genesis_url, help='URL to genesis file (default official genesis)')
    parser.add_argument('-f', '--force', action='store_true')

    args = parser.parse_args()

    return args


def decide_action(args):

    bin_path = sys.argv[0]
    daemon_running = get_daemon_pid()

    if args.action == 'start':

        if daemon_running and args.force:
            action_signal(args.working_dir, signal.SIGKILL, 'forced stop')
        elif daemon_running and not args.force:
            eprint("adsd already started. To force kill and start, use `{0} -f start`.".format(bin_path))
            sys.exit(1)

        action_start(args.working_dir)

    elif args.action == 'stop':

        if not daemon_running:
            print("adsd not running. To start, use `{0} start`.".format(bin_path))
            sys.exit(0)
        if args.force:
            action_signal(args.working_dir, signal.SIGKILL, 'forced stop')
        else:
            action_signal(args.working_dir, signal.SIGTERM, 'stop')

    elif args.action == 'restart':

        if not daemon_running:
            eprint("adsd not running. To start, use `{0} start`.".format(bin_path))
            sys.exit(1)

        action_signal(args.working_dir, signal.SIGUSR1, 'restart')

    elif args.action == 'configure':

        if daemon_running and not args.force:
            eprint("adsd is running. Please stop it first, using `{0} stop` or `{0} --force stop`.".format(bin_path))
            sys.exit(1)
        elif daemon_running and args.force:
            action_signal(args.working_dir, signal.SIGKILL, 'forced stop')

        action_configure(args)

    elif args.action == 'status':

        if daemon_running:
            print("adsd is running.")
        else:
            print("adsd is not running.")


if __name__ == '__main__':

    prepped_args = prepare_args()
    validate_platform()
    decide_action(prepped_args)
